name: NoEstasSola
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  google_maps_flutter: ^2.0.1
  flutter_verification_code: ^0.2.1
  pin_code_fields: ^6.1.0
  flare_flutter: ^2.0.6
  bouncing_widget: ^1.2.3
  beauty_textfield: ^0.0.1
  firebase_auth: ^1.0.1
  camera: ^0.5.8+5
  path_provider:
  path:
  firebase_ml_vision: ^0.9.6+2
  image:
  curved_navigation_bar: ^0.3.7
  location: ^4.1.1
  geolocator: ^7.0.1
  http: ^0.12.0+2
  google_place: ^0.4.0
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  flutter_polyline_points: ^0.2.4
  geocoder: ^0.2.1
  slimy_card: ^1.0.4
  video_player: ^2.0.2
  firebase_storage: ^8.0.0
  shared_preferences: ^2.0.5
  path_provider_windows: ^2.0.0
  tflite_flutter: ^0.6.0
  lite_rolling_switch: ^0.1.1
  dropdown_formfield: ^0.1.3
  uuid: 3.0.2
  bitmap: ^0.1.2
  fluttertoast: ^8.0.3
  image_picker: ^0.7.3
  flutter_sms: ^2.3.1
  social_share: ^2.1.1
  url_launcher: ^6.0.3
  loading_gifs: ^0.3.0
  flutter_launcher_icons: ^0.9.0


flutter_icons:
  android: "launcher_icon"
  image_path_android: "assets/Icon/Lu_icono_driver.png"
  image_path_ios: "assets/Icon/Lu_icono_user.png"
  ios: true 

  
dependency_overrides:
  http: ^0.13.0


    



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/mobilefacenet.tflite
    - assets/Logo/Logo_lala_app.png
    - assets/Logo/Lu_logo.png
    - assets/Logo/Conductora.png
    - assets/Logo/Usuaria.png
    - assets/video/carga.mp4
    - assets/Logo/Lu_verde.png
    - assets/Logo/lu_back.png
    - assets/Logo/Blog_icono.png
    - assets/Logo/Lu_yellow.png
    - assets/Logo/Lu_red.png
    - assets/IconosMarker/Auto.png
    - assets/IconosMarker/Lu_red.png
    - assets/IconosMarker/Lu_yellow.png
    - assets/IconosMarker/Markers.png
    - assets/IconosMarker/Lu_yellow_sombra.png
    - assets/IconosMarker/Marker_1.png
    - assets/IconosMarker/Marker_2.png
    - assets/IconosMarker/Marker_3.png
    - assets/IconosMarker/Marker_4.png
    - assets/video/Lu_carga.mp4
    - assets/Logo/Lu_carga_transparente.gif
  fonts:
    - family: Gotham
      fonts: 
        - asset: fonts/GothamRounded-Bold.otf
        - asset: fonts/GothamRounded-BoldItalic.otf
        - asset: fonts/GothamRounded-Book.otf
        - asset: fonts/GothamRounded-BookItalic.otf
        - asset: fonts/GothamRounded-Light.otf
        - asset: fonts/GothamRounded-LightItalic.otf
        - asset: fonts/GothamRounded-Medium.otf
        - asset: fonts/GothamRounded-MediumItalic.otf
        - asset: fonts/GothamRoundedBold_21016.ttf
        - asset: fonts/GothamRoundedBook_21018.ttf
        - asset: fonts/GothamRoundedLight_21020.ttf
        - asset: fonts/GothamRoundedMedium_21022.ttf
        

