name: NoEstasSola
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  google_maps_flutter: ^2.0.1
  flutter_verification_code: ^0.2.1
  pin_code_fields: ^6.1.0
  flare_flutter: ^2.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

